/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "RCC_interface.h"
#include "GPIO_interface.h"
#include "NVIC_interface.h"


/*first application to test interrupts enable / disable */
/*int main(void)
{
	RCC_AHB1EnableClk(AHB1_GPIOA);
	GPIO_PinConfig_t LEDPin={
			.Mode = OUTPUT,
			.PinNum = PIN5,
			.Port = PORTA,
			.OutputType = PUSH_PULL,
			.PullType = NOPULL
	};

	GPIO_u8PinInit(&LEDPin);
	NVIC_u8Enable(USART3);
	NVIC_u8SetPending(USART3);
	NVIC_u8Disable(USART3);

	 Loop forever
	for(;;);
}


void USART3_IRQHandler(void)
{
	GPIO_u8SetPinValue(PORTA, PIN5, PIN_HIGH);
}*/

/*Second application to test interrupts Priority */

int main(void)
{
	RCC_AHB1EnableClk(AHB1_GPIOA);
	GPIO_PinConfig_t LEDPin={
			.Mode = OUTPUT,
			.PinNum = PIN5,
			.Port = PORTA,
			.OutputType = PUSH_PULL,
			.PullType = NOPULL
	};

	GPIO_u8PinInit(&LEDPin);
	SCB_u8SetPeriorityGroup(SixteenGroups_OneSub);
	NVIC_u8Enable(EXTI0);
	NVIC_u8Enable(EXTI1);
	NVIC_u8IRQPeriority(EXTI0, Level_5);
	NVIC_u8IRQPeriority(EXTI1, Level_8);
	NVIC_u8SetPending(EXTI1);

}

void EXTI0_IRQHandler(void)
{
	GPIO_u8SetPinValue(PORTA, PIN5, PIN_HIGH);
}

void EXTI1_IRQHandler(void)
{
	GPIO_u8SetPinValue(PORTA, PIN5, PIN_LOW);
	NVIC_u8SetPending(EXTI0);
}
