/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "RCC_interface.h"
#include "GPIO_interface.h"

int main(void)
{
	RCC_AHB1EnableClk(AHB1_GPIOA);
	GPIO_PinConfig_t LEDPin={
			.Mode = OUTPUT,
			.PinNum = PIN5,
			.Port = PORTA,
			.OutputType = PUSH_PULL,
			.PullType = NOPULL
	};

	GPIO_u8PinInit(&LEDPin );
	GPIO_u8SetPinValue(PORTA, PIN5, PIN_HIGH);
    /* Loop forever */
	for(;;);
}
